name: ubt
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'auth'
        required: true
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Installing Xubuntu-desktop ENV (wait for 10 min)
      run: sudo apt update && sudo apt install xfce4 -y && sudo apt-get install xubuntu-desktop -y
      
    - name: instalcrd
      run: |
           wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo dpkg --install google-chrome-stable_current_amd64.deb
           sudo apt install --assume-yes --fix-broken
    - name: conf
      run: |
           sudo apt install nautilus expect nano -y
           sudo apt install --assume-yes xscreensaver
    - name: installcrd
      run: |
           sudo apt-get update
           sudo apt-get install xbase-clients python3-psutil xvfb -y
           wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
           sudo dpkg --install chrome-remote-desktop_current_amd64.deb
           sudo apt install --assume-yes --fix-broken
    - name: generate script
      run: |
           touch setup.sh
           echo "${{ github.event.inputs.auth }}" >> "setup.sh"
           chmod 777 setup.sh
    - name: initialize
      run: |   
           expect -c '
           spawn ./setup.sh
           expect "Enter a PIN of at least six digits: "
           send "123456\r"
           expect "Enter the same PIN again: "
           send "123456\r"
           expect eof
           '
    - uses: jakejarvis/wait-action@master
      with:
        time: '400m'
